services:

  test-mongo:
    image: "mongo:5.0"
    container_name: my-mongo
    ports:
      - 27017:27017

  test-app:
    build: ./
    container_name: test-app
    ports:
      - 3030:3030
    links:
      - test-mongo
