services:

  test-mongo:
    image: "mongo:5.0"
    container_name: my-mongo
    networks:
      - backend
  test-app:
    image: "mytestdocker:latest"
    container_name: test-app
    ports:
      - 3030:3030
    links:
      - test-mongo
    networks:
      - backend
networks:
  backend:
    name: "my_test_network"