version: '3'
services:
  test-mongo:
    image: "mongo:5.0"
    container_name: my-mongo
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  test-postgres:
    image: "postgres:9.6.5"
    container_name: postgres-db
    networks:
      - backend
    environment:
        POSTGRES_DB: postgres_db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: mysecretpassword
  test-app:
    depends_on:
      - test-mongo
      - test-postgres
    environment:
      - TEST_MONGO_ADDRESS=my-mongo
    build: .
    container_name: test-app
    ports:
      - 3030:3030
    links:
      - test-mongo
    networks:
      - backend
    volumes:
      - ./users.db:/users.db
    env_file:
      - ./dev.env
networks:
  backend:
    name: "my_test_network"
    driver: bridge