apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    purpose: mongo_db
spec:
  containers:
  - name: mongo-container
    image: mongo:5.0
    ports:
    - containerPort: 27015
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: root
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: example

  - name: myapp-container
    image: rusttest:runtime
    ports:
    - containerPort: 3030
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: root
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: example
    - name: DATABASE_URL
      value: users.db
    - name: TEST_MONGO_ADDRESS
      value: my-mongo