apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: belyaevmihail/rusttest
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        - name: DATABASE_URL
          value: /usr/users.db
        - name: TEST_MONGO_ADDRESS
          value: mongo-pod
        volumeMounts:               # 3
        - name: sqlite-volume       # 3.a
          mountPath: /usr        # 3.b
      volumes:
      - name: sqlite-volume         # 2
        persistentVolumeClaim:
          claimName: sqlite-pvc     # 