apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    purpose: my_rust_app
spec:
  containers:
  - name: myapp-container
    image: rusttest:runtime
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: root
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: example
    - name: DATABASE_URL
      value: users.db
      
TEST_MONGO_ADDRESS=my-mongo