name: Rust

on:
  pull_request:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test my_test
    - name: Run mongo tests
      run: cargo test testsmongo -- --test-threads=1
    - name: Run login tests
      run: cargo test testlogin
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run coverage
      run: ./tools/coberage.sh
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

